// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID        int32
	UserID    uuid.UUID
	Amount    int32
	Incoming  interface{}
	Recurring string
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
