// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, amount, incoming, description, recurring, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, amount, incoming, description, recurring, start_date, end_date
`

type CreateTransactionParams struct {
	UserID      uuid.UUID
	Amount      float64
	Incoming    bool
	Description string
	Recurring   string
	StartDate   sql.NullTime
	EndDate     sql.NullTime
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Incoming,
		arg.Description,
		arg.Recurring,
		arg.StartDate,
		arg.EndDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Incoming,
		&i.Description,
		&i.Recurring,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getUserIncomingTransactions = `-- name: GetUserIncomingTransactions :many
SELECT id, user_id, amount, incoming, description, recurring, start_date, end_date FROM transactions WHERE user_id = $1 AND incoming = 1
`

func (q *Queries) GetUserIncomingTransactions(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserIncomingTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Incoming,
			&i.Description,
			&i.Recurring,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOutgoingTransactions = `-- name: GetUserOutgoingTransactions :many
SELECT id, user_id, amount, incoming, description, recurring, start_date, end_date FROM transactions WHERE user_id = $1 AND incoming = 0
`

func (q *Queries) GetUserOutgoingTransactions(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserOutgoingTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Incoming,
			&i.Description,
			&i.Recurring,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT id, user_id, amount, incoming, description, recurring, start_date, end_date FROM transactions WHERE user_id = $1
`

func (q *Queries) GetUserTransactions(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Incoming,
			&i.Description,
			&i.Recurring,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactionsByMonth = `-- name: GetUserTransactionsByMonth :many
SELECT id, user_id, amount, incoming, description, recurring, start_date, end_date FROM transactions 
WHERE user_id = $1 AND start_date <= $2 AND end_date >= $3
`

type GetUserTransactionsByMonthParams struct {
	UserID    uuid.UUID
	StartDate sql.NullTime
	EndDate   sql.NullTime
}

func (q *Queries) GetUserTransactionsByMonth(ctx context.Context, arg GetUserTransactionsByMonthParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getUserTransactionsByMonth, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Incoming,
			&i.Description,
			&i.Recurring,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
